# Generated by Django 3.1.2 on 2021-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210226_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userA',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pics/None'),
        ),
    ]
